# Generated by Django 4.0.3 on 2022-05-21 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djeotree", "0002_tag_tagvalue"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tag",
            options={
                "ordering": ("user", "title"),
                "verbose_name": "Tag",
                "verbose_name_plural": "Tags",
            },
        ),
        migrations.RemoveField(
            model_name="family",
            name="parent",
        ),
        migrations.AddField(
            model_name="family",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                help_text="Choose tags attached to this family",
                through="djeotree.TagValue",
                to="djeotree.tag",
                verbose_name="Tags",
            ),
        ),
    ]
