# Generated by Django 4.0.3 on 2022-05-21 18:15

import django.db.models.deletion
import django.utils.timezone
import djgeojson.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djeotree", "0003_alter_tag_options_remove_family_parent_family_tags"),
    ]

    operations = [
        migrations.CreateModel(
            name="Element",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "intro",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                ("body", models.TextField(null=True, verbose_name="Text")),
                (
                    "date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Date"
                    ),
                ),
                ("location", djgeojson.fields.PointField()),
                (
                    "private",
                    models.BooleanField(default=False, verbose_name="Private element"),
                ),
                (
                    "family",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="family_element",
                        to="djeotree.family",
                        verbose_name="Family",
                    ),
                ),
            ],
            options={
                "verbose_name": "Element",
                "verbose_name_plural": "Elements",
            },
        ),
        migrations.CreateModel(
            name="ElementTagValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        help_text="Tag value", max_length=200, verbose_name="Value"
                    ),
                ),
                (
                    "element",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="element_value",
                        to="djeotree.element",
                        verbose_name="Element",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="element_tag_value",
                        to="djeotree.tag",
                        verbose_name="Tag",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tag value",
                "verbose_name_plural": "Tag values",
            },
        ),
    ]
