# Generated by Django 4.0.3 on 2022-05-21 18:24

import django.db.models.deletion
import filebrowser.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djeotree", "0004_element_elementtagvalue"),
    ]

    operations = [
        migrations.CreateModel(
            name="ElementImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="Used in captions",
                        max_length=200,
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "fb_image",
                    filebrowser.fields.FileBrowseField(
                        max_length=200, null=True, verbose_name="Image"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        max_length=200,
                        null=True,
                        upload_to="uploads/images/element/",
                        verbose_name="Image",
                    ),
                ),
                (
                    "position",
                    models.PositiveSmallIntegerField(
                        null=True, verbose_name="Position"
                    ),
                ),
                (
                    "element",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="element_image",
                        to="djeotree.element",
                        verbose_name="Article",
                    ),
                ),
            ],
            options={
                "verbose_name": "Element image",
                "verbose_name_plural": "Element images",
                "ordering": ["position"],
            },
        ),
    ]
