# Generated by Django 4.0.3 on 2022-06-04 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("djeotree", "0006_remove_family_tags"),
    ]

    operations = [
        migrations.RenameField(
            model_name="element",
            old_name="location",
            new_name="geom",
        ),
    ]
