# Generated by Django 4.0.3 on 2022-06-08 17:37

import djgeojson.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djeotree", "0007_rename_location_element_geom"),
    ]

    operations = [
        migrations.AddField(
            model_name="family",
            name="geom",
            field=djgeojson.fields.MultiLineStringField(null=True),
        ),
        migrations.AlterField(
            model_name="element",
            name="body",
            field=models.TextField(blank=True, null=True, verbose_name="Text"),
        ),
        migrations.AlterField(
            model_name="element",
            name="intro",
            field=models.CharField(
                max_length=200, null=True, verbose_name="Description"
            ),
        ),
    ]
