# Generated by Django 4.0.3 on 2022-06-16 21:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djeotree", "0010_alter_element_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="element",
            name="date",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Date"
            ),
        ),
    ]
