# Generated by Django 4.0.3 on 2022-06-20 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("djeotree", "0011_alter_element_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tag",
            options={
                "ordering": ("title",),
                "verbose_name": "Tag",
                "verbose_name_plural": "Tags",
            },
        ),
        migrations.RemoveField(
            model_name="family",
            name="user",
        ),
        migrations.RemoveField(
            model_name="tag",
            name="user",
        ),
    ]
