# Generated by Django 4.0.3 on 2022-07-04 12:30

import djgeojson.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("djeotree", "0012_alter_tag_options_remove_family_user_remove_tag_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="element",
            name="geom",
            field=djgeojson.fields.PointField(verbose_name="Location"),
        ),
    ]
