# Generated by Django 4.0.3 on 2022-07-08 10:35

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("djeotree", "0013_alter_element_geom"),
    ]

    operations = [
        migrations.AlterField(
            model_name="element",
            name="body",
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name="Text"),
        ),
    ]
